{% set name = "pyiron_atomistics" %}
{% set version = "0.6.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fc86a5694379a11f2e2e5c3934082d1fb37ce2cb5610a98b0c34c48a4587c09

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - ase
    - atomistics
    - defusedxml
    - h5py
    - matplotlib-base
    - mendeleev
    - mp-api
    - numpy >=1.26.0
    - pandas
    - phonopy
    - pint
    - pyiron_base
    - pyiron_snippets
    - pylammpsmpi
    - pyscal3
    - scipy
    - scikit-learn
    - seekpath
    - spglib
    - structuretoolkit
    - versioneer
    - toml
  run:
    - python >=3.9,<3.13
    - ase >=3.22.1,<=3.23.0
    - atomistics >=0.1.27,<=0.1.32
    - defusedxml >=0.7.0,<=0.7.1
    - h5py >=3.9.0,<=3.11.0
    - matplotlib-base >=3.5.3,<=3.9.2
    - mendeleev >=0.12.0,<=0.17.0
    - mp-api >=0.37.0,<=0.42.2
    - numpy >=1.26.0,<=1.26.4
    - pandas >=2.0.3,<=2.2.3
    - phonopy >=2.20.0,<=2.26.6
    - pint >=0.18,<=0.24.3
    - pyiron_base >=0.10.0,<=0.10.2
    - pyiron_snippets >=0.1.3,<=0.1.4
    - pylammpsmpi >=0.2.18,<=0.2.25
    - pyscal3 >=3.2.5,<=3.2.7
    - scipy >=1.11.1,<=1.14.1
    - scikit-learn >=1.2.1,<=1.5.2
    - seekpath >=1.9.5,<=2.1.0
    - spglib >=2.0.2,<=2.5.0
    - structuretoolkit >=0.0.27,<=0.0.28

test:
  imports:
    - pyiron_atomistics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_atomistics
  summary: pyiron - an integrated development environment (IDE) for computational materials science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
