schema_version: 1

context:
  name: pyiron_atomistics
  version: 0.7.12
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 5433a755ee4e55bd213f622d97dbfb7570ec3f8f6c288fa0227cec3fd71244da

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
    - ase
    - atomistics
    - defusedxml
    - h5py
    - matplotlib-base
    - mendeleev
    - mp-api
    - numpy >=1.26.0
    - pandas
    - phonopy
    - pint
    - pyiron_lammps
    - pyiron_base
    - pyiron_snippets
    - pyiron_vasp
    - pylammpsmpi
    - pyscal3
    - scipy
    - scikit-learn
    - seekpath
    - spglib
    - structuretoolkit
    - versioneer
    - toml
    - sphinx_parser
  run:
    - python >=${{ python_min }},<3.13
    - ase >=3.23.0,<=3.25.0
    - atomistics >=0.1.33,<=0.2.5
    - defusedxml >=0.7.0,<=0.7.1
    - h5py >=3.9.0,<=3.13.0
    - matplotlib-base >=3.5.3,<=3.10.1
    - mendeleev ==0.19.0
    - mp-api >=0.37.0,<=0.45.7
    - numpy ==1.26.4
    - pandas >=2.0.3,<=2.3.1
    - phonopy >=2.20.0,<=2.41.1
    - pint >=0.18,<=0.24.4
    - pyiron_base >=0.13.0,<=0.13.3
    - pyiron_lammps >=0.3.2,<=0.4.3
    - pyiron_snippets >=0.1.3,<=0.1.4
    - pyiron_vasp >=0.2.2,<=0.2.7
    - pylammpsmpi >=0.2.18,<=0.2.37
    - pyscal3 >=3.2.5,<=3.2.7
    - scipy >=1.15.0,<=1.15.2
    - scikit-learn >=1.2.1,<=1.6.1
    - seekpath >=1.9.5,<=2.1.0
    - spglib >=2.0.2,<=2.6.0
    - structuretoolkit >=0.0.29,<=0.0.32
    - sphinx_parser ==0.0.2

tests:
  - python:
      imports:
        - pyiron_atomistics
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: pyiron - an integrated development environment (IDE) for computational materials science.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/pyiron_atomistics

extra:
  recipe-maintainers:
    - niklassiemer
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
