schema_version: 1

context:
  name: pyiron_atomistics
  version: "0.8.0"
  python_min: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 13aa25e10d3a536a9666938914acce9e07136f1e4f0b8c97f2cbb6c2d25621b3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - ase
    - atomistics
    - defusedxml
    - h5py
    - matplotlib-base
    - mendeleev
    - mp-api
    - numpy >=1.26.0
    - pandas
    - phonopy
    - pint
    - pyiron_lammps
    - pyiron_base
    - pyiron_snippets
    - pyiron_vasp
    - pylammpsmpi
    - pyscal3
    - scipy
    - scikit-learn
    - seekpath
    - spglib
    - structuretoolkit
    - hatchling
    - hatch-vcs
    - sphinx_parser
  run:
    - python >=${{ python_min }},<3.13
    - ase >=3.23.0,<=3.26.0
    - atomistics =0.3.0
    - defusedxml >=0.7.0,<=0.7.1
    - h5py >=3.12.1,<=3.14.0
    - matplotlib-base >=3.9.1,<=3.10.6
    - mendeleev =1.1.0
    - mp-api >=0.37.0,<=0.45.11
    - numpy >=2.2.1,<=2.3.3
    - pandas >=2.2.3,<=2.3.2
    - phonopy >=2.26.6,<=2.43.2
    - pint =0.24.4
    - pyiron_base >=0.13.0,<=0.15.2
    - pyiron_lammps >=0.3.2,<=0.4.7
    - pyiron_snippets >=0.1.3,<=0.2.0
    - pyiron_vasp >=0.2.2,<=0.2.13
    - pylammpsmpi >=0.2.36,<=0.3.3
    - pyscal3 >=3.2.5,<=3.3.0
    - scipy >=1.15.0,<=1.16.2
    - scikit-learn >=1.4.2,<=1.7.2
    - seekpath >=1.9.5,<=2.1.0
    - spglib >=2.5.0,<=2.6.0
    - structuretoolkit =0.0.35
    - sphinx_parser =0.1.1

tests:
  - python:
      imports:
        - pyiron_atomistics
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: pyiron - an integrated development environment (IDE) for computational materials science.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/pyiron_atomistics

extra:
  recipe-maintainers:
    - niklassiemer
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
