travis:
  secure:
    BINSTAR_TOKEN: pY8rPpfz+tiJVu+yhzQA0gaoTe+HbxAyWIXSsBTpB8ywNX09mtlBM2gNK6NF8GY+TH4mQfFV+yGYHDAP2Vr5FBU5wZLLpef4kpOMRuS01QJs475GtmrAM5tsF8ZaE7GMz7l79J4V/cZL2YEACzpZCWbB6X7IuguAQEZWrjtmlGBD4E5f1++ec5fHJxUCsUtxbgHrwmqTz+VBlEpa51Ll09Tf7l6HGR/HYN13seRJoYuOBx7JX5hexNzfKnZ/ZUE3RgyF0uazT2ssCubiQm2EPJ1HtrpT1K5MhhU0QwREuJeSsHmGoqXodshYMS+p0b4b8WcrRsoVGqyjWjYPV79h+QCDdpZ49+QtQWesWQAtXGAjseatColtdnvOVgK8YUfRWUjhWQqdHp3pORKszrKJzYnvnTiDJUkztFZWWoI7OqacmLohyzdPpvRW6a5CW3MHbbogOzW4R+GwcbD3Zpit3pbR1LsfEHWKz3mtKykq62EYXd8Jq77MIU4PGCZdvjxW+LZGs4UWQKHJ2jNB8V6dIKHrrMnhyzqJAP568CUQtOZYXqEIWCKD0yFjX5imMvl4/UYA1mWVuNTHIupUjdgmzSfUZMmY3OkDqyE0rIzh9QJAo1/QCTvT7geWmDHi4YSmw3RnbAfHzeB+Ci+hA1ok8p1jh/IB8ky3O+KT9/+aMzg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
